name: Theatre
favicon: null
layout_spectrum: 0.8539024088531733
typography_spectrum: 0.4473761459812522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.07462268485687673
  lightness: 0.5733896405436099
  saturation: 0.38471309025771916
  rhythmicContrast: 0.8668393020052463
purpose: []
